### Problem Statement

you are hired by a venture capitalist to predict the profit of the startup. For that you have to deal with a dataset which contains the details of 50 startups and predict the profit of the new startup based on certain features. Based on your decision and predictios, whether one should invest in a perticular startup or not.

Dataaset contains the following fields: R&D Spend- Total amount of money spent on research and development Administration-
Total amount of money spent on administration, Marketing spent- Total amount of money spent on Marketing,States- the state where startups operates,Profit- profit earned by startups


you have to perform following task before applying machine learning algorithms

1) Handeling Missing values 2) Prepare data for training and testing 3)Apply decision tree algorithms to train the model 

In [1]:
import pandas as pd
import numpy as np

In [5]:
data= pd.read_csv(r'C:\Users\Anu\Downloads\50_Startups.csv')

In [6]:
data.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [7]:
data.shape

(50, 5)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [9]:
data.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [10]:
data.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [11]:
features = data.iloc[:,:-1].values
label = data.iloc[:,[-1]].values

In [12]:
features

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [13]:
label

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [19]:
# Convert categorical feature to numerical feature as sklearn only work with numpy array
# Instead of label encoding and then one hot coding
# newer version directly work with one hot encoding using column transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
transfrormer = ColumnTransformer(transformers=[('OneHot',OneHotEncoder(),[3])],remainder='passthrough')

In [20]:
features = transfrormer.fit_transform(features.tolist())
features

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [21]:
# Devide the data into test and train
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test = train_test_split(features,label,test_size=0.2,random_state=1)

In [34]:
# Apply Desion tree algorithm
from sklearn.tree import DecisionTreeRegressor
DTR = DecisionTreeRegressor(max_depth=3)
DTR.fit(X_train,y_train)
                        

DecisionTreeRegressor(max_depth=3)

In [35]:
# Checking the scores for training and testing as well
print(DTR.score(X_train,y_train))
print(DTR.score(X_test,y_test))

0.9719776806321837
0.8784483297473074


Model is not generalized. We may check for other values of max_depth. max_depth generally is odd value. We may check for 5,7,9...and check for training and testing score and choose the model with with generalize score.


In [ ]:
# Check with max_depth 5

In [36]:

DTR = DecisionTreeRegressor(max_depth=5)
DTR.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=5)

In [37]:
print(DTR.score(X_train,y_train))
print(DTR.score(X_test,y_test))

0.9995250727754222
0.9041902543587961


In [ ]:
# Check with max_depth 7

In [38]:

DTR = DecisionTreeRegressor(max_depth=7)
DTR.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=7)

In [39]:
print(DTR.score(X_train,y_train))
print(DTR.score(X_test,y_test))

1.0
0.900265669963024


In [ ]:
# Check with max_depth 7

In [41]:
DTR = DecisionTreeRegressor(max_depth=9)
DTR.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=9)

In [42]:
print(DTR.score(X_train,y_train))
print(DTR.score(X_test,y_test))

1.0
0.9254642749463493
